# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Check(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.personal_photo = QtWidgets.QPushButton(self.centralwidget)
        self.personal_photo.setGeometry(QtCore.QRect(30, 80, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.personal_photo.setFont(font)
        self.personal_photo.setObjectName("personal_photo")
        self.paper_photo = QtWidgets.QPushButton(self.centralwidget)
        self.paper_photo.setGeometry(QtCore.QRect(30, 150, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.paper_photo.setFont(font)
        self.paper_photo.setObjectName("paper_photo")
        self.agree_photo = QtWidgets.QPushButton(self.centralwidget)
        self.agree_photo.setGeometry(QtCore.QRect(30, 220, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.agree_photo.setFont(font)
        self.agree_photo.setObjectName("agree_photo")
        self.tabel_photo = QtWidgets.QPushButton(self.centralwidget)
        self.tabel_photo.setGeometry(QtCore.QRect(30, 290, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabel_photo.setFont(font)
        self.tabel_photo.setObjectName("tabel_photo")
        self.achives_photo = QtWidgets.QPushButton(self.centralwidget)
        self.achives_photo.setGeometry(QtCore.QRect(30, 360, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.achives_photo.setFont(font)
        self.achives_photo.setObjectName("achives_photo")
        self.join_agree_photo = QtWidgets.QPushButton(self.centralwidget)
        self.join_agree_photo.setGeometry(QtCore.QRect(30, 420, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.join_agree_photo.setFont(font)
        self.join_agree_photo.setObjectName("join_agree_photo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.personal_photo.setText(_translate("MainWindow", "Фото на личное дело"))
        self.paper_photo.setText(_translate("MainWindow", "Паспорт"))
        self.agree_photo.setText(_translate("MainWindow", "Согласие на ОПД"))
        self.tabel_photo.setText(_translate("MainWindow", "Аттестат"))
        self.achives_photo.setText(_translate("MainWindow", "Индивидуальные достижения"))
        self.join_agree_photo.setText(_translate("MainWindow", "Согласие на зачисление"))
